tree:main.o CreateBiTree.o PreOrderTraverse.o InOrderTraverse.o PostOrderTraverse.o GetMaxDepth.o LeafNodeNum.o LevelNodeNum.o CountNode.o SearchNode.o CopyBiTree.o DestroyBiTree.o BST.o HuffmanTree.o
	gcc -o tree main.o CreateBiTree.o PreOrderTraverse.o InOrderTraverse.o PostOrderTraverse.o GetMaxDepth.o LeafNodeNum.o LevelNodeNum.o CountNode.o SearchNode.o CopyBiTree.o DestroyBiTree.o BST.o HuffmanTree.o

main.o:
	gcc -c main.c -o main.o

CreateBiTree.o:
	gcc -c CreateBiTree.c -o CreateBiTree.o

PreOrderTraverse.o:
	gcc -c PreOrderTraverse.c -o PreOrderTraverse.o

InOrderTraverse.o:
	gcc -c InOrderTraverse.c -o InOrderTraverse.o

PostOrderTraverse.o:
	gcc -c PostOrderTraverse.c -o PostOrderTraverse.o

GetMaxDepth.o:
	gcc -c GetMaxDepth.c -o GetMaxDepth.o

LeafNodeNum.o:
	gcc -c LeafNodeNum.c -o LeafNodeNum.o

LevelNodeNum.o:
	gcc -c LevelNodeNum.c -o LevelNodeNum.o

CountNode.o:
	gcc -c CountNode.c -o CountNode.o

SearchNode.o:
	gcc -c SearchNode.c -o SearchNode.o

CopyBiTree.o:
	gcc -c CopyBiTree.c -o CopyBiTree.o

DestroyBiTree.o:
	gcc -c DestroyBiTree.c -o DestroyBiTree.o

BST.o:
	gcc -c BST.c -o BST.o

HuffmanTree.o:
	gcc -c HuffmanTree.c -o HuffmanTree.o

.PHONY rm:
	rm *.o tree